version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - '3000:3000'
    env_file: .env
    depends_on:
      - database

  database:
    image: 'postgres:12.1-alpine'
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: .env

  redis:
    image: 'redis:6-alpine'
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - web
      - database
      - redis
    volumes:
      - .:/app
    env_file: .env
    entrypoint: ./entrypoints/sidekiq_entrypoint.sh

volumes:
  postgres:
