default: &default
  adapter: postgresql
  encoding: unicode

  database: <%= ENV['DATABASE_NAME'] %>
  port:     <%= ENV['DATABASE_PORT'] %>
  host:     <%= ENV['DATABASE_HOST'] %>

  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

  pool:     <%= ENV['RAILS_MAX_THREADS'] || 5 %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
