local:
  service: Disk
  root: <%= Rails.root.join('storage') %>

pg:
  service: PostgreSQL

mirror:
  service: Mirror
  primary: local
  mirrors: [ pg ]

test:
  service: Disk
  root: <%= Rails.root.join('tmp/storage') %>
